language: java
services:
  - postgresql
jobs:
  include:
    - stage:
      name: "Test App Build"
      script:
        - chmod +x Scripts/app_build.sh
        - bash ./Scripts/app_build.sh;
        - echo "Completed App Build";
    - stage:
      name: "Test Server Build"
      before_script:
        - psql -c 'create database postgres;' -U postgres
      script:
        - chmod +x Scripts/server_build.sh
        - bash ./Scripts/server_build.sh
        - echo "Completed Server Build"