#language: java
#
#script:
#  - chmod +x Application/app_build.sh
#  - cd Application/
#  - ./app_build.sh
#  - cd ..
#  - chmod +x Server/server_build.sh
#  - cd Server/
#  - ./server_build.sh

language: java

jobs:
  include:
    - stage:
      name: "Test App Build"
      script: bash ./Scripts/app_build.sh; echo "HIIIIIIIII";
    - stage:
      name: "Test Server Build"
      script: bash ./Scripts/server_build.sh